twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your images live
        public/img/: img

when@test:
    twig:
        strict_variables: true
#        form_themes: [ 'bootstrap_5_layout.html.twig' ]